config/routes.rb
Rails.application.routes.draw do

  resources :users
  root 'events#index'
  # get '/events/:id' => 'events#show'
  # post '/events/show' => 'events#show'
  get '/search', to: 'events#index', as: 'search'
  get '/events/sync_to_calendar' => 'events#sync_to_calendar'

  resources :events do
    collection do
      get :dashboard
    end
  end


  # these routes are for showing users a login form, logging them in, and logging them out.
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'


  root 'sessions#user'
  match "/auth/google_oauth2/callback" => "sessions#google_create", via: [:get, :post]

  get "/signout" => "sessions#destroy", :as => :signout

  # These routes will be for signup. The first renders a form in the browse, the second will
  # receive the form and create a user in our database using the data given to us by the user.
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

      # get '/redirect', to: 'example#redirect', as: 'redirect'
      # get '/callback', to: 'example#callback', as: 'callback'

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  @current_user = User.find(5)
  @location = @current_user.city

  def self.get_info(params)
    if params[:q].blank?
      query = @location
    else
      query = params[:q] +"%"+ params[:city]
    end

    res = EventBriteApi.new("https://www.eventbriteapi.com/v3/events/search/", { q:query }).event_getter
  end

  def self.get_ticket_info(params)
    params[:keyword] = params[:q]
    if params[:keyword].blank?
      data = @location
    else
      data = "#{params[:keyword]} + #{params[:city]}"
    end
  result = TicketMasterApi.new("https://app.ticketmaster.com/discovery/v2/events.json?apikey=#{ENV['TICKET_API_KEY']}",{keyword:data}).ticketm_getter
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def dashboard
    @current_user = User.find(5)
    @events = @current_user.events
  end

  def index
    @event_brite_events = Event.get_info(params)
    @ticketm_events     = Event.get_ticket_info(params)
  end

  def show
    # @event = params
    @current_user = User.find(5)
    @current_user.events.create(source: params[:event_source],source_id: params[:event_source_id],description: params[:event_description],photo: params[:event_photo],price: params[:event_price],date: params[:event_date])
    render json: params
  end


 def create
    @current_user = User.find(5)
    event = @current_user.events.create(source: params[:event_source],source_id: params[:event_source_id],description: params[:event_description],photo: params[:event_photo],price: params[:event_price],date: params[:event_date])
    redirect_to dashboard_events_path()
  end

  def search
    @event_brite_events = Event.get_info(params)
    @ticketm_events     = Event.get_ticket_info(params)
    render  'list'
    end



  def destroy

    @event.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_events_path(), notice: 'Your Dock Event was successfully destroyed.' }
      format.json { head :no_content }

    end
  end


end

private

def set_event
  @event = Event.find_by_id(params[:id])
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_calendar_form.html.erb
<%= form_with(url: '/events/sync_to_calendar') do %>
<<<<<<< HEAD
<%= text_field_tag :event  %>
<%= text_field_tag :description  %>
<%= text_field_tag :dates %>
<%= button_to 'Sync To Calendar', { :controller => "events", :action => "sync_to_calendar" } %>
=======
  <%= text_field_tag :event  %>
  <%= text_field_tag :description  %>
  <%= text_field_tag :dates %>
  <%= button_to 'Sync To Calendar', { :controller => "events", :action => "sync_to_calendar" } %>
>>>>>>> 95d96aa1551f21af64044a496902d208c41b53a3
<% end %>

app/views/events/_event_form.html.erb
<%= form_tag( { :controller => "events", :action => "create" }, method: "post", local: true) do |form| %>

<p><% key['logo'] %></p>
<%= image_tag key['logo']['url'] if key['logo'] %></p>
<p><% key ["description"]["text"].truncate(400)%></p>


<% image = key['logo']['url'] if key['logo'] %>
<% title = key ["name"]["text"]%>
<% date = key ["start"]["local"].in_time_zone.strftime("%a, %B %m at %I:%M%p")%>

<% if key ["is_free"] == false %>
<% "Paid Event" %>
<% else %>
<% "Free Event" %>
<% end %>
  <% unless key["description"]["text"].nil? %>
  <% description = key["description"]["text"].truncate(400) %>
  <% else %>
  <% description = nil %>
  <% end %>



  <%= hidden_field_tag(:event_source_id, key["id"]) %>
  <%= hidden_field_tag(:event_source, title) %>
  <%= hidden_field_tag(:event_date, date) %>
  <%= hidden_field_tag(:event_photo, image) %>
  <%= hidden_field_tag(:event_description, description) %>
  <% if key ["is_free"] == false %>


    <%= hidden_field_tag(:event_price, "Paid Event") %>
    <% else %>
    <%= hidden_field_tag(:event_price, "Free Event") %>
    <% end %>


     <div class="actions">
      <%= submit_tag "Dock It" %>
    </div>

<<<<<<< HEAD
    <div class="sync-to-calendar">
=======
    <div class="actions">
>>>>>>> 95d96aa1551f21af64044a496902d208c41b53a3
      <%= link_to "Sync To Calendar", "https://calendar.google.com/calendar/render?action=TEMPLATE&text=#{title}&#{date}&#{description},+link+here:+http://www.example.com&location=549+NW+28+street+10022&sf=true&output=xml",	{:target=>"_blank"} %>
    </div>

<% end %>

app/views/events/_event_info_modal.html.erb
<div class="modal fade" id="myModal_<%= index %>" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= key ["name"]["text"]%></h4>
      </div>
      <div class="modal-body">
        <p><%= key ["description"]["text"]%></p>

          <%= render partial: 'event_form', locals: { key: key }%>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/events/_event_info_ticket.html.erb
<div class="modal fade" id="mytkModal_<%= index %>" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><strong><p><%= tk ["name"]%></p></strong></h4>
      </div>
      <div class="modal-body">
        <div class="col-sm-5">
          <img class="img-thumbnail ticket-img"<%= image_tag tk["images"][1]["url"] if ["images"] %>
        </div>


        <strong><p><%= tk ["name"]%></p></strong>

        <strong>On Sale</strong><br>

          <p>Start Date: <%= tk["sales"]["public"]["startDateTime"].in_time_zone.strftime("%a, %B %m at %I:%M%p")%>
          <br>
          End Date:  <%= tk["sales"]["public"]["endDateTime"].in_time_zone.strftime("%a, %B %m at %I:%M%p")%></p>

          <div class="ticket_price">

            <%unless tk["priceRanges"] == nil %>
            <% @min = tk["priceRanges"][0]["min"] %>
            <% @max = tk["priceRanges"][0]["max"]  %>
                <% if @min == @max %>
                <%= "Ticket Price: Just #{@min}0" %>
                <% else %>
                <%= "Ticket Price: From #{@min}0 to #{@max}0" %>
                <% end %>
            <%= tk["priceRanges"][0]["currency"]%>.
            <% end %>
          </div>


          <%= render partial: 'event_ticket_form', locals: { tk: tk }%>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/events/_event_ticket_form.html.erb
<%= form_tag( { :controller => "events", :action => "create" }, method: "post", local: true) do %>

<!--  Ticket Master-->
<!-- pop-up screen event info to send to dock -->

<img class="img-thumbnail ticket-img"<%= image_tag tk["images"][1]["url"] if tk["images"] %>
<%#=  tk ["name"]%>

<!-- send to dashboard -->
<% image =  tk["images"][1]["url"].html_safe if tk["images"] %>
<% title =  tk ["name"]%>
<% date = tk["sales"]["public"]["startDateTime"].in_time_zone.strftime("%a, %B %m at %I:%M%p")%>

  <% description = tk ["name"]%>

<%#= tk["sales"]["public"]["startDateTime"].in_time_zone.strftime("%a, %B %m at %I:%M%p")%>
 <%#= tk["sales"]["public"]["endDateTime"].in_time_zone.strftime("%a, %B %m at %I:%M%p")%>



          <%#unless tk["priceRanges"] == nil %>
          <%# @min = tk["priceRanges"][0]["min"] %>
          <%# @max = tk["priceRanges"][0]["max"]  %>
              <%# if @min == @max %>
              <%#= "Ticket Price: Just #{@min}0" %>
              <%# else %>
              <%#= "Ticket Price: From #{@min}0 to #{@max}0" %>
              <%# end %>
          <%#= tk["priceRanges"][0]["currency"]%>.
          <%# end %>








<!-- END send info to dashboard -->

  <%#= tk["sales"]["public"]["endDateTime"].in_time_zone.strftime("%a, %B %m at %I:%M%p")%>



 <%= hidden_field_tag(:event_source_id, tk["id"]) %>
 <%= hidden_field_tag(:event_source, title) %>
 <%= hidden_field_tag(:event_date, date) %>
 <%= hidden_field_tag(:event_photo, image) %>
 <%= hidden_field_tag(:event_description, description) %>
 <div class="actions">
  <%= submit_tag "Dock It" %>
</div>

<div class="actions">
  <%= link_to "Sync To Calendar", "https://calendar.google.com/calendar/render?action=TEMPLATE&text=#{title}&#{date}&#{description},+link+here:+http://www.example.com&location=549+NW+28+street+10022&sf=true&output=xml",	{:target=>"_blank"} %>
</div>

   <% end %>

app/views/events/_list.html.erb
<!--  Eventbrite API Filter and some CSS with BS -->
<%@event_brite_events.parsed_response["events"].each_with_index do |key, index|%>
<!--  File for testin API, full info-->
<p><% key %><% index %></p>
<!--  start event for eventbrite -->
<!-- <img class="img-thumbnail" <%= image_tag key['original']['url'] if key['original'] %> -->

<div class="container">
  <div class="row">
    <div class="col-sm-5">
      <% x = image_tag key['logo']['url'] if key['logo'] %>
      <% if x == nil %>
      <img class="img-thumbnail" <%= image_tag('events-pholder.jpg') %>
      <% else %>
      <img class="img-thumbnail" <%= image_tag key['logo']['url'] if key['logo'] %>
      <% end %>
    </div>
    <div class="col-sm-6">
      <div class="dock_event">

        <strong><p><%= key ["name"]["text"]%></p></strong>
        <p><%= key ["start"]["local"].in_time_zone.strftime("%a, %B %m at %I:%M%p")  %></p>
<p><%#= key ["start"]["local"].in_time_zone.strftime("%Y%m%dT%H%M%SZ")  %></p>
          <strong>

            <% if key ["is_free"] == false %>
            <%= "Paid Event" %>
            <% else %>
            <%= "Free Event" %>
            <% end %>

          </strong>

        <% unless key["description"]["text"].nil? %>
        <p><%= key["description"]["text"].truncate(400)%></p>
        <% end %>

        <!--Button trigger modal -->
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal_<%= index %>">
          More Info
        </button>
      </div>
    </div>
  </div>
  <span>
    <!-- <hr style="border-bottom:1px solid red;"> -->
  </span>
</div>


    <%= render partial: 'event_info_modal', locals: { index: index, key: key }%>

<% end %>


<!--  TicketMaster API Filter and some CSS with BS -->

<% @ticketm_events.parsed_response["_embedded"]["events"].each_with_index do |tk, index|%>
<!--  File for testin API, full info-->
 <% tk  %>
<!--  start event for ticketmaster -->
<div class="container">
<div class="row">
  <div class="col-sm-5">
    <img class="img-thumbnail ticket-img"<%= image_tag tk["images"][1]["url"] if tk["images"] %>
  </div>
  <div class="col-sm-6">
    <div class="dock_event">

      <strong><p><%= tk ["name"]%></p></strong>

      <strong>On Sale</strong><br>

        <p>Start Date: <%= tk["sales"]["public"]["startDateTime"].in_time_zone.strftime("%a, %B %m at %I:%M%p")%>
        <br>
        End Date:  <%= tk["sales"]["public"]["endDateTime"].in_time_zone.strftime("%a, %B %m at %I:%M%p")%></p>

        <div class="ticket_price">

          <%unless tk["priceRanges"] == nil %>
          <% @min = tk["priceRanges"][0]["min"] %>
          <% @max = tk["priceRanges"][0]["max"]  %>
              <% if @min == @max %>
              <%= "Ticket Price: Just #{@min}0" %>
              <% else %>
              <%= "Ticket Price: From #{@min}0 to #{@max}0" %>
              <% end %>
          <%= tk["priceRanges"][0]["currency"]%>.
          <% end %>
        </div>

        <!--Button trigger modal -->
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#mytkModal_<%= index %>">
          More Info
        </button>
      </div>
    </div>
  </div>
    </span>
      <!-- <hr style="border-bottom:1px solid red;"> -->
    </span>
</div>
<%= render partial: 'event_info_ticket', locals: { index:index, tk:tk } %>
<% end %>

app/views/events/dashboard.html.erb
<section>

<% @events.each do |d| %>


<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <% d.source_id%><br>
      <img class="img-thumbnail ticket-img" src="<%=d.photo%>">
      <!-- 410x210 -->
    </div>
    <div class="col-sm-6">
      <div class="dock_event">
        <strong><%= d.source %></strong>

        <p>
        <%= d.date %>
      </p>
      <p>
        <strong><%= d.price %></strong>
      </p>
      <p>
      <%= d.description %>
    </p>
    <button type="button" id="delete_btn" class="btn btn-primary btn-lg"><%= link_to 'DELETE', event_path(d.id), method: :delete, data: { confirm: 'Are you sure?' } %></button>

  </div>
</div>
<span>
  <hr style="border-bottom:1px solid red;">
</span>
<% end%>

app/views/events/index.html.erb
<!-- # <%= form_tag(search_path, method: "get") do %><br>
#   <p>Search for Events:</p>
#   <%= text_field_tag([:q]) %>
#   <%= text_field_tag(:city, nil, :required => true) %><span> *City Required.</span><br>
#   <br>
#   <div><%= submit_tag("Search") %></div>
#
# <% end %> -->





<h1>Events</h1>
<div class="events-list">
  <%= render 'list' %>
</div>

<!-- Sign Up Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Sign Up!</h4>
      </div>
      <div class="modal-body">
        <div class="signup_form">

        <%= form_for :user, url: '/users', html: { multipart: true } do |f| %>
          ProfilePic: <%= f.file_field :avatar %>
          <%= f.text_field :name, placeholder: "Name" %>
          <%= f.text_field :email, placeholder: "Email" %>
          <%= f.password_field :password, placeholder: "Password" %>
          <%= f.password_field :password_confirmation, placeholder: "Password confirmation" %>
          <%= f.text_field :zipcode, placeholder: "Zipcode" %>


        </div>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Create", class: "btn btn-primary" %>
              <% end %>
        <!-- <button type="button" class="btn btn-primary" id="Create-btn">Save changes</button> -->
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Login Modal -->
<div class="modal fade" id="myModal_login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Login</h4>
      </div>
      <div class="modal-body">
        <div class="login_form">

          <%= form_tag :login, url: '/login', html: { multipart: true }  do %>

            Email: <%= text_field_tag :email %>
            Password: <%= password_field_tag :password %>

            <%= link_to "Sign in with Google", "/auth/google_oath2" %>




        </div>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= submit_tag "Login", class: "btn btn-primary" %>
              <% end %>
        <!-- <button type="button" class="btn btn-primary" id="Create-btn">Save changes</button> -->
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!-- Half Page Image Background Carousel Header -->
    <!-- <header id="myCarousel" class="carousel slide">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol> -->

        <!-- Wrapper for Slides -->
        <!-- <div class="carousel-inner">
            <img class="item active" src="../assets/intro-bg.jpg" alt="Los Angeles"></div>


                <div class="carousel-caption">
                    <h2>Caption 1</h2>
                </div>

      <img class="item" src="../assets/intro-bg.jpg" alt="Los Angeles">
      <div class="carousel-caption">
                    <h2>Caption 2</h2>
                </div> -->


            <!-- <div class="item">
              <img src="../assets/intro-bg.jpg" alt="Los Angeles">
            </div>
                <div class="carousel-caption">
                    <h2>Caption 3</h2>
                </div> -->


        <!-- Controls -->
        <!-- <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>

    </header> -->


    <div class="events-list">
    <%= image_tag('Upcoming-Events.jpg')  %>
  </div>

      <%= render 'list' %>

app/views/events/show.html.erb
<h1>Hello</h1>




<!-- <h1>description</h1>
<%= @event[:desc] %> -->

app/views/events/sync_to_calendar.html.erb
<h4>Your Event Has Been Synched To Your Calendar</h4>
<%= render 'calendar_form' %>